version: '3'

services:
  app:
    container_name: LinkShortener
    build:
      context: ./
    ports:
      - "8081:8081"
    expose:
      - 8081
    depends_on:
      - db

  db:
    container_name: LinkShortener-db
    image: postgres:13.0-alpine
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: mypassword
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
