// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.0
// source: src.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinkShorterClient is the client API for LinkShorter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkShorterClient interface {
	Post(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Get(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type linkShorterClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkShorterClient(cc grpc.ClientConnInterface) LinkShorterClient {
	return &linkShorterClient{cc}
}

func (c *linkShorterClient) Post(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/api.LinkShorter/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShorterClient) Get(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/api.LinkShorter/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkShorterServer is the server API for LinkShorter service.
// All implementations must embed UnimplementedLinkShorterServer
// for forward compatibility
type LinkShorterServer interface {
	Post(context.Context, *AddRequest) (*AddResponse, error)
	Get(context.Context, *AddRequest) (*AddResponse, error)
}

// UnimplementedLinkShorterServer must be embedded to have forward compatible implementations.
type UnimplementedLinkShorterServer struct {
}

func (UnimplementedLinkShorterServer) Post(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedLinkShorterServer) Get(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedLinkShorterServer) mustEmbedUnimplementedLinkShorterServer() {}

// UnsafeLinkShorterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkShorterServer will
// result in compilation errors.
type UnsafeLinkShorterServer interface {
	mustEmbedUnimplementedLinkShorterServer()
}

func RegisterLinkShorterServer(s grpc.ServiceRegistrar, srv LinkShorterServer) {
	s.RegisterService(&LinkShorter_ServiceDesc, srv)
}

func _LinkShorter_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShorterServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.LinkShorter/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShorterServer).Post(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShorter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShorterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.LinkShorter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShorterServer).Get(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkShorter_ServiceDesc is the grpc.ServiceDesc for LinkShorter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkShorter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.LinkShorter",
	HandlerType: (*LinkShorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Post",
			Handler:    _LinkShorter_Post_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _LinkShorter_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src.proto",
}
